package org.mbe.configSchedule.generator;

import org.mbe.configSchedule.util.Machine;
import org.mbe.configSchedule.util.SchedulingProblem;
import org.mbe.configSchedule.util.Task;

import java.io.IOException;
import java.util.*;
import java.util.stream.Stream;

import static java.lang.Math.floor;

public class JSSPGenerator extends SPGenerator {

    /**
     * Generates a job-shop scheduling-problem with the parameters
     *
     * @param jobCount             Number of jobs
     * @param taskCount            Number of mandatory tasks
     * @param durationOutlierCount Number of duration Outliers (tasks that take longer than usual)
     * @param machineCount         Number of machines
     * @param optionalCount        Number of optional tasks
     * @param altCount             Number of alternative tasks
     * @param altGroupCount        Number of alternative task groups
     * @param deadline             Deadline
     * @param durationConstraints  Number of duration constraints
     * @param maxDurationRequires  Maximum number of duration constraints originating from one task
     * @param name                 Name of the problem
     * @return the generated scheduling problem.
     * @throws IOException
     */
    public SchedulingProblem generateProblem(int jobCount, int taskCount,
                                int durationOutlierCount, int machineCount, int optionalCount,
                                int altCount, int altGroupCount, int deadline, int durationConstraints, int maxDurationRequires, String name) throws IOException {
        List<List<Task>> jobs = new ArrayList<>();

        if (jobCount > taskCount) {
            System.err.println("Please enter more tasks than jobs");
        }

        // Fill the necessary lists (jobs and machines)
        List<Machine> machines = createMachines(machineCount);
        List<Task> mandatoryTasksWithVarDuration = new ArrayList<>();
        createStandardJobs(taskCount, jobCount, durationOutlierCount, machines, jobs, mandatoryTasksWithVarDuration);
        List<Task> optionalTasks = createOptionalTasks(optionalCount, machines);
        List<Task[]> alternativeTaskGroups = createAlternativeTasks(altCount, altGroupCount, machines);
        // Each optional task and each task in an alternative group is its own job
        jobs.addAll(optionalTasks.stream().map(List::of).toList());
        jobs.addAll(alternativeTaskGroups.stream().map(Arrays::asList).distinct().toList());

        createDurationConstraints(
                Stream.concat(optionalTasks.stream().map(t -> new Task[] {t}), alternativeTaskGroups.stream()).toList(),
                mandatoryTasksWithVarDuration, durationConstraints, maxDurationRequires
        );

        List<Task> tasks = jobs.stream().flatMap(Collection::stream).toList();
        Map<Task, List<Task>> precedenceOrder = new HashMap<>();
        for (List<Task> job : jobs) {
            for (int i = 1; i < job.size(); i++) {
                Task dependent = job.get(i);
                Task dependency = job.get(i - 1);
                precedenceOrder.put(dependent, List.of(dependency));
            }
        }

        return new SchedulingProblem(name, tasks, precedenceOrder, machines, deadline);
    }

    /**
     * Creates the standard jobs for the problem generated by the Problem Generator
     *
     * @param taskCount                     The total number of tasks (to be created)
     * @param jobCount                      The number of jobs (to be created)
     * @param durationOutlierCount          The number of tasks with a duration that lies outside the "normal" range
     * @param machines                      The number of machines
     * @param jobs                          List of jobs
     * @param mandatoryTasksWithVarDuration List of mandatory tasks that have a variable duration
     */
    private void createStandardJobs(int taskCount, int jobCount, int durationOutlierCount,
                                    List<Machine> machines, List<List<Task>> jobs, List<Task> mandatoryTasksWithVarDuration) {
        double tasksPerJobD = (double) taskCount / jobCount;
        int tasksPerJob = (int) floor(tasksPerJobD);
        int restTasks = taskCount % tasksPerJob;
        int tasksInJob;

        boolean firstJob = true;
        int taskID = 1;

        for (int i = 0; i < jobCount; i++) {
            List<Task> job = new ArrayList<>();

            // If this is the first job, the excess-tasks should be in this job
            if (firstJob) {
                tasksInJob = tasksPerJob + restTasks;
                firstJob = false;
            } else {
                tasksInJob = tasksPerJob;
            }

            for (int j = 0; j < tasksInJob; j++) {
                // If there are equal to or more durationOutlier than tasks to be created,
                // then the task has to be an outlier
                boolean onlyOutliersLeft = (taskCount - taskID) <= durationOutlierCount;
                boolean outLierChance = this.random.nextBoolean();
                boolean isOutlier = durationOutlierCount > 0 && (onlyOutliersLeft || outLierChance);
                durationOutlierCount--;

                Task task = createRandomTask("p" + taskID, false, machines, isOutlier);
                if (task.hasUncertainDurations() && !task.hasUnboundDurations()) {
                    mandatoryTasksWithVarDuration.add(task);
                }
                taskID++;
                job.add(task);
            }
            jobs.add(job);
        }
    }
}
