package org.mbe.configSchedule.generator;

import org.mbe.configSchedule.util.Machine;
import org.mbe.configSchedule.util.SchedulingProblem;
import org.mbe.configSchedule.util.Task;

import java.io.IOException;
import java.util.*;
import java.util.stream.Stream;

import static java.lang.Math.floor;

public class JSSPGenerator extends SPGenerator {

    /**
     * Generates a job-shop scheduling-problem with the parameters
     *
     * @param jobCount             Number of jobs
     * @param taskCount            Number of mandatory tasks
     * @param durationOutlierCount Number of duration Outliers (tasks that take longer than usual)
     * @param machineCount         Number of machines
     * @param optionalCount        Number of optional tasks
     * @param altCount             Number of alternative tasks
     * @param altGroupCount        Number of alternative task groups
     * @param deadline             Deadline
     * @param durationConstraints  Number of duration constraints
     * @param maxDurationRequires  Maximum number of duration constraints originating from one task
     * @param name                 Name of the problem
     * @throws IOException
     */
    public void generateProblem(int jobCount, int taskCount,
                                int durationOutlierCount, int machineCount, int optionalCount,
                                int altCount, int altGroupCount, int deadline, int durationConstraints, int maxDurationRequires, String name) throws IOException {
        List<List<Task>> jobs = new ArrayList<>();

        if (jobCount > taskCount) {
            System.err.println("Please enter more tasks than jobs");
        }

        // Fill the necessary lists (jobs and machines)
        List<Machine> machines = createMachines(machineCount);
        List<Task> mandatoryTasksWithVarDuration = new ArrayList<>();
        createStandardJobs(taskCount, jobCount, durationOutlierCount, machines, jobs, mandatoryTasksWithVarDuration);
        List<Task> optionalTasks = createOptionalTasks(optionalCount, machines);
        List<Task[]> alternativeTaskGroups = createAlternativeTasks(altCount, altGroupCount, machines);
        // Each optional task and each task in an alternative group is its own job
        jobs.addAll(optionalTasks.stream().map(List::of).toList());
        jobs.addAll(alternativeTaskGroups.stream().map(Arrays::asList).distinct().toList());

        createDurationConstraints(
                Stream.concat(optionalTasks.stream().map(t -> new Task[] {t}), alternativeTaskGroups.stream()).toList(),
                mandatoryTasksWithVarDuration, durationConstraints, maxDurationRequires
        );

        List<Task> tasks = jobs.stream().flatMap(Collection::stream).toList();
        Map<Task, List<Task>> precedenceOrder = new HashMap<>();
        for (List<Task> job : jobs) {
            for (int i = 1; i < job.size(); i++) {
                Task dependent = job.get(i);
                Task dependency = job.get(i - 1);
                precedenceOrder.put(dependent, List.of(dependency));
            }
        }

        SchedulingProblem sp = new SchedulingProblem(name + "_jssp", tasks, precedenceOrder, machines, deadline);
        writeToFile(sp);
    }

    /**
     * Creates the standard jobs for the problem generated by the Problem Generator
     *
     * @param taskCount                     The total number of tasks (to be created)
     * @param jobCount                      The number of jobs (to be created)
     * @param durationOutlierCount          The number of tasks with a duration that lies outside the "normal" range
     * @param machines                      The number of machines
     * @param jobs                          List of jobs
     * @param mandatoryTasksWithVarDuration List of mandatory tasks that have a variable duration
     */
    private void createStandardJobs(int taskCount, int jobCount, int durationOutlierCount,
                                    List<Machine> machines, List<List<Task>> jobs, List<Task> mandatoryTasksWithVarDuration) {
        double tasksPerJobD = (double) taskCount / jobCount;
        int tasksPerJob = (int) floor(tasksPerJobD);
        int restTasks = taskCount % tasksPerJob;
        int tasksInJob;

        boolean firstJob = true;
        int taskID = 1;

        for (int i = 0; i < jobCount; i++) {
            List<Task> job = new ArrayList<>();

            // If this is the first job, the excess-tasks should be in this job
            if (firstJob) {
                tasksInJob = tasksPerJob + restTasks;
                firstJob = false;
            } else {
                tasksInJob = tasksPerJob;
            }

            for (int j = 0; j < tasksInJob; j++) {
                // If there are equal to or more durationOutlier than tasks to be created,
                // then the task has to be an outlier
                boolean onlyOutliersLeft = (taskCount - taskID) <= durationOutlierCount;
                boolean outLierChance = this.random.nextBoolean();
                boolean isOutlier = durationOutlierCount > 0 && (onlyOutliersLeft || outLierChance);
                Task task = createRandomTask("p" + taskID, false, machines, isOutlier);
                if (task.hasUncertainDurations() && !task.hasUnboundDurations()) {
                    mandatoryTasksWithVarDuration.add(task);
                }
                taskID++;
                job.add(task);
            }
            jobs.add(job);
        }
    }

    /**
     * Parses the given scheduling problem to the UVL-format
     *
     * @param sp SchedulingProblem-Object for which the UVL-file is to be created
     * @return String in the format of a UVL-file
     */
    @Override
    protected String parseToUVL(SchedulingProblem sp) {
        StringBuilder uvlString = new StringBuilder();
        uvlString.append("features").append(System.lineSeparator());
        uvlString.append("\t").append(sp.getName()).append(" {featuredescription__ '").append(sp.getDeadline()).append("', abstract true}").append(System.lineSeparator());
        uvlString.append("\t\tmandatory").append(System.lineSeparator());
        uvlString.append("\t\t\t\"dl = ").append(sp.getDeadline()).append("\"").append(System.lineSeparator());

        List<String>[] cons = parseTasks(sp, uvlString);
        parseMachines(sp.getMachines(), uvlString);
        parseConstraints(cons, uvlString);

        return uvlString.toString();
    }

    /**
     * Parses the tasks of the jobs with their characterisitics, e.g. duration. Appends the features to the String started in parseToUVL
     *
     * @param sp        Contains the generated scheduling problem
     * @param uvlString The UVL-string to be appended
     * @return Returns constraints for task order, excluding tasks, durations and machine
     */
    private List<String>[] parseTasks(SchedulingProblem sp, StringBuilder uvlString) {
        uvlString.append("\t\t\tP {abstract true}").append(System.lineSeparator());

        // TODO: Parse unbound durations

        List<Task> mandatoryTasks = new ArrayList<>();
        List<Task> optionalTasks = new ArrayList<>();

        List<String> taskOrderCons = new ArrayList<>();
        List<String> excludeCons = new ArrayList<>();
        List<String> durationCons = new ArrayList<>();
        List<String> machineCons = new ArrayList<>();

        for (Task task : sp.getTasks()) {
            if (task.isOptional()) {
                optionalTasks.add(task);
            } else {
                mandatoryTasks.add(task);
            }
        }

        uvlString.append("\t\t\t\tmandatory").append(System.lineSeparator());
        for (Task task : mandatoryTasks) {
            parseTask(task, uvlString, machineCons);

            for (Task dependency : sp.getPrecedenceOrder().getOrDefault(task, new ArrayList<>())) {
                taskOrderCons.add("\t%s => %s%n".formatted(task.getName(), dependency.getName()));
            }

            // Task-duration-constraints
            if (!task.getDurationCons().isEmpty()) {
                for (Map.Entry<Integer, List<Task>> taskDurationCon : task.getDurationCons().entrySet()) {
                    List<Task> requiredTasks = taskDurationCon.getValue();
                    for (Task requiredTask : requiredTasks) {
                        durationCons.add("\t\"d%s = %d\" => %s%n".formatted(task.getName(), taskDurationCon.getKey(), requiredTask.getName()));
                    }
                }
            }

        }

        List<String> excludeTasksAlreadyHandled = new ArrayList<>();
        uvlString.append("\t\t\t\toptional").append(System.lineSeparator());
        for (Task task : optionalTasks) {
            parseTask(task, uvlString, machineCons);

            if (!task.getExcludeTasks().isEmpty() && !excludeTasksAlreadyHandled.contains(task.getName())) {
                excludeTasksAlreadyHandled.addAll(task.getExcludeTasks());

                List<String> alternativeGroup = new ArrayList<>(task.getExcludeTasks());
                alternativeGroup.add(task.getName());

                StringBuilder excludeConString = new StringBuilder();
                excludeConString.append("\t");
                for (int i = 0; i < alternativeGroup.size(); i++) {
                    excludeConString.append("(");
                    for (int j = 0; j < alternativeGroup.size(); j++) {
                        if (i == j) {
                            excludeConString.append(alternativeGroup.get(j));
                        } else {
                            excludeConString.append("!").append(alternativeGroup.get(j));
                        }

                        if (j < alternativeGroup.size() - 1) {
                            excludeConString.append(" & ");
                        }
                    }
                    excludeConString.append(")");
                    if (i < alternativeGroup.size() - 1) {
                        excludeConString.append(" | ");
                    }
                }
                excludeConString.append(System.lineSeparator());

                excludeCons.add(excludeConString.toString());
            }
        }


        @SuppressWarnings("unchecked")
        List<String>[] cons = new List[4];
        cons[0] = taskOrderCons;
        cons[1] = excludeCons;
        cons[2] = durationCons;
        cons[3] = machineCons;

        return cons;
    }

    /**
     * Appends the task as a feature with durations and its machine constraints.
     *
     * @param task        The task to parse.
     * @param uvlString   The UVL-String to be appended.
     * @param machineCons The machine constraints list to be appended.
     */
    private void parseTask(Task task, StringBuilder uvlString, List<String> machineCons) {
        uvlString.append("\t\t\t\t\t").append(task.getName()).append(System.lineSeparator());

        List<String> durationFeatureStrings = new ArrayList<>();

        String durationStringTemplate = "\t\t\t\t\t\t\t\"d" + task.getName() + " = %d\"";
        for (int duration : task.getDurations()) {
            durationFeatureStrings.add(durationStringTemplate.formatted(duration));
        }
        String unboundDurationStringTemplate = durationStringTemplate.replace("=", ">=");
        task.getUnboundDurations().ifPresent(
                integer -> durationFeatureStrings.add(unboundDurationStringTemplate.formatted(integer))
        );

        uvlString.append("\t\t\t\t\t\t");
        uvlString.append(durationFeatureStrings.size() == 1 ? "mandatory" : "alternative");
        uvlString.append(System.lineSeparator());
        uvlString.append(String.join(System.lineSeparator(), durationFeatureStrings));
        uvlString.append(System.lineSeparator());

        machineCons.add("\t%s => %s%n".formatted(task.getName(), task.getMachine().getName()));
    }

    /**
     * Appends the features for the machines to the UVL-string
     *
     * @param machines  List of machines
     * @param uvlString The UVL-String to be appended
     */
    private void parseMachines(List<Machine> machines, StringBuilder uvlString) {
        uvlString.append("\t\t\tM {abstract true}").append(System.lineSeparator());
        uvlString.append("\t\t\t\tmandatory").append(System.lineSeparator());

        for (Machine machine : machines) {
            uvlString.append("\t\t\t\t\t").append(machine.getName()).append(System.lineSeparator());
        }
    }

    /**
     * Appends the constraints to the UVL-String
     *
     * @param cons      List of constraints
     * @param uvlString The UVL-String to be appended
     */
    private void parseConstraints(List<String>[] cons, StringBuilder uvlString) {
        uvlString.append("constraints").append(System.lineSeparator());
        for (List<String> conType : cons) {
            for (String con : conType) {
                uvlString.append(con);
            }
        }
    }
}
