package org.mbe.configSchedule.generator;

import org.mbe.configSchedule.util.Machine;
import org.mbe.configSchedule.util.PathPreferences;
import org.mbe.configSchedule.util.SchedulingProblem;
import org.mbe.configSchedule.util.Task;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

import static java.lang.Math.floor;

public abstract class SPGenerator {
    protected final Random random = new Random();

    /**
     * Generates random machines
     *
     * @param machineCount The number of machines (to be created)
     * @return List of machines
     */
    protected List<Machine> createMachines(int machineCount) {
        List<Machine> machines = new ArrayList<>();
        for (int i = 0; i < machineCount; i++) {
            Machine machine = new Machine("m" + (i + 1), false);
            machines.add(machine);
        }
        return machines;
    }

    /**
     * Generate durations for the given task.
     *
     * <p>There is a 50% chance for generating multiple durations or only a single one.
     *
     * @param task                   the task for which to generate durations.
     * @param maxAmount              the maximum amount of durations.
     * @param minimum                the minimum duration.
     * @param variability            the variability of the durations on top of the minimum amount.
     * @param unboundDurationsChance the inverse chance to generate unbound durations.
     */
    protected void setRandomDurations(Task task, int maxAmount, int minimum, int variability, int unboundDurationsChance) {
        boolean variableDurationChance = this.random.nextBoolean();
        if (variableDurationChance) {
            int durationCount = this.random.nextInt(1, maxAmount + 1);
            for (int i = 0; i < durationCount; i++) {
                task.addDuration(this.random.nextInt(minimum, variability + 1));
            }
        } else {
            int duration = this.random.nextInt(minimum, variability + 1);
            task.setDurations(new int[] {duration});
        }

        if (unboundDurationsChance > 0 && this.random.nextInt(unboundDurationsChance) == 0) {
            int lowerBound = this.random.nextInt(minimum, variability + 1);
            task.setUnboundDurations(lowerBound);
        }
    }

    protected Task createRandomTask(String name, boolean optional, List<Machine> machines, boolean isOutlier) {
        Task task = new Task();
        task.setName(name);
        task.setMachine(machines.get(this.random.nextInt(machines.size())));

        if (isOutlier) {
            setRandomDurations(task, 4, 6, 10, 4);
        } else {
            setRandomDurations(task, 4, 1, 5, 0);
        }

        task.setOptional(optional);
        return task;
    }

    /**
     * Creates the optional tasks for the problem generated by the Problem Generator
     *
     * @param optionalCount The number of optional tasks to be created
     * @param machines      List of machines
     * @return List of optionalTasks
     */
    protected List<Task> createOptionalTasks(int optionalCount, List<Machine> machines) {
        List<Task> optionalTasks = new ArrayList<>();
        for (int i = 0; i < optionalCount; i++) {
            Task task = createRandomTask("po" + (i + 1), true, machines, false);

            optionalTasks.add(task);
        }
        return optionalTasks;
    }

    /**
     * Creates the duration constraints for the problem generated by the Problem Generator
     *
     * @param optionalTasks                 List with arrays of optional tasks. Optional Tasks are arrays with one task, alternative task groups are arrays with multiple tasks
     * @param mandatoryTasksWithVarDuration List with mandatory tasks that have a variable duration
     * @param durationConstraints           int that determines the number of durations that are part of a duration constraint
     * @param maxDurationRequires           int that determines the number of constraints originating from one duration
     */
    protected void createDurationConstraints(List<Task[]> optionalTasks, List<Task> mandatoryTasksWithVarDuration,
                                             int durationConstraints, int maxDurationRequires) {
        if (optionalTasks.isEmpty()) {
            System.err.println("No optional tasks present. Cannot generate duration constraints.");
            return;
        }

        // Check if there are enough mandatory Tasks for the number of durationConstraints
        if (durationConstraints > mandatoryTasksWithVarDuration.size()) {
            System.err.printf("Not enough mandatory tasks with variable durations for durationConstraints %d, set to %d.%n",
                    durationConstraints, mandatoryTasksWithVarDuration.size());
            durationConstraints = mandatoryTasksWithVarDuration.size();
        }

        // Check if there are enough optional Tasks for the max. amount
        // of Duration-Constraints originating from one task
        if (maxDurationRequires > optionalTasks.size()) {
            System.err.printf("Not enough optional/ alternative tasks for maxDurationRequires %d, set to %d.%n",
                    maxDurationRequires, optionalTasks.size());
            maxDurationRequires = optionalTasks.size();

        }

        for (Task task : mandatoryTasksWithVarDuration.subList(0, durationConstraints)) {
            int[] durations = task.getDurations();
            int durationForConstraint = durations[this.random.nextInt(durations.length)];

            List<Task[]> possibleOptionalTasks = new ArrayList<>(optionalTasks);
            List<Task> requiredTasks = new ArrayList<>();
            for (int j = 0; j < maxDurationRequires; j++) {
                Task[] taskGroup = possibleOptionalTasks.remove(this.random.nextInt(possibleOptionalTasks.size()));

                Task requiredTask = taskGroup[this.random.nextInt(taskGroup.length)];
                requiredTasks.add(requiredTask);
            }

            task.addDurationCon(durationForConstraint, requiredTasks);
        }
    }

    /**
     * Creates the alternative task groups for the problem generated by the Problem Generator
     *
     * @param altCount      The total number of tasks belonging to alternative task groups (to be created)
     * @param altGroupCount The number of alternative task groups (to be created)
     * @param machines      List of machines
     * @return List of alternative groups
     */
    protected List<Task[]> createAlternativeTasks(int altCount, int altGroupCount, List<Machine> machines) {
        // Check if there even are alternative tasks to be created
        if (altCount <= 0 || altGroupCount <= 0) {
            return List.of();
        }

        if (altGroupCount > altCount) {
            altGroupCount = altCount / 2;
            System.out.printf("""
                    Number of alternative groups must be greater than number of alternative tasks.
                    Set number of groups to %d (every group consists of 2 tasks).
                    """, altGroupCount);
        }

        // Calculate how many tasks belong in one group
        // If there are e.g. 5 tasks and 2 groups -> g1 = (1,2,3), g2 = (4,5)
        int tasksPerGroup = (int) floor((double) altCount / altGroupCount);
        int restTasksAlt = altCount % tasksPerGroup;
        int tasksInGroup;

        boolean firstGroup = true;

        List<Task[]> alternativeTaskGroups = new ArrayList<>();
        int taskId = 1;
        for (int i = 0; i < altGroupCount; i++) {
            // If it's the first group that is created, then it should include the surplus of tasks
            if (firstGroup) {
                tasksInGroup = tasksPerGroup + restTasksAlt;
                firstGroup = false;
            } else {
                tasksInGroup = tasksPerGroup;
            }

            // Task-array that, at the end, contains all the tasks belonging to one alternative task group
            Task[] group = new Task[tasksInGroup];

            // Create tasks for the group
            for (int j = 0; j < tasksInGroup; j++) {
                Task task = createRandomTask("pa" + taskId++, true, machines, false);
                task.setExcludeTasks(new ArrayList<>());
                group[j] = task;
            }

            alternativeTaskGroups.add(group);

            // Every task in the group has a list with the other tasks of the group
            // These are the tasks that the task exludes
            // If there is the group (1,2,3) -> ExcludeTasks(1) = {2,3}
            for (int j = 0; j < group.length; j++) {
                for (int k = 0; k < group.length; k++) {
                    if (j != k) {
                        group[j].getExcludeTasks().add(group[k].getName());
                    }
                }
            }
        }

        return alternativeTaskGroups;
    }
}
