package org.mbe.configSchedule.util;
import java.util.*;
import java.util.stream.Collectors;

/**
 * The structure of a given schedule
 */
public class ScheduleStructure {

    private final Map<Machine,List<Task>> structure = new HashMap<>();

    /**
     * Structure generated by a given schedule
     */
    public ScheduleStructure(Schedule schedule)
    {
        for (Machine machine : schedule.getActiveMachines()) {
            List<Task> taskOrder = schedule.getTasks(machine).stream()
                    .sorted(Comparator.comparingInt(AssignedTask::getStart))
                    .map(AssignedTask::getTask)
                    .toList();
            structure.put(machine, taskOrder);
        }
    }

    /**
     * Generalized Structure generated by given values
     */
    public ScheduleStructure(Map<Machine,List<Task>> generalizedStructure)
    {
        this.structure.putAll(generalizedStructure);
    }

    /**
     * Return the order of tasks for a specific machine
     *
     * @param machine the machine for which to get the order of tasks.
     * @return list which contains task order for given machine.
     */
    public List<Task> getTaskOrder(Machine machine)
    {
        if(this.structure.containsKey(machine))
        {
            return Collections.unmodifiableList(this.structure.get(machine));
        }
        return List.of();
    }

    /**
     * Return task amount of the structure
     *
     * @return int number of the task amount
     */
    public int getTotalTaskCount() {
        return this.structure.values().stream().mapToInt(List::size).sum();
    }

    /**
     * Return all machines of the structure
     *
     * @return a set of machines
     */
    public Set<Machine> getMachines()
    {
        return Collections.unmodifiableSet(this.structure.keySet());
    }

    /**
     * Check if the current structure contains the given structure in order of: size -> machines -> tasks
     *
     * @return true if structure contains given structure, false if not
     */
    public boolean containsStructure(ScheduleStructure otherStructure)
    {
        if(this.structure.size() < otherStructure.structure.size())
        {
            return false;
        }
        else if (!this.getMachines().stream().map(Machine::getName).collect(Collectors.toSet()).equals(otherStructure.getMachines().stream().map(Machine::getName).collect(Collectors.toSet())))
        {
            return false;
        }
        for(Machine machine : this.getMachines())
        {
            List<Task> thisTaskOrder = this.getTaskOrder(machine);
            List<Task> otherTaskOrder = otherStructure.getTaskOrder(machine);

            int i = 0;
            for(Task task : thisTaskOrder)
            {
                if(i < otherTaskOrder.size() && task.getName().equals(otherTaskOrder.get(i).getName()))
                {
                    i++;
                }
            }
            if(i != otherTaskOrder.size())
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Generalize all unique structures into a single all-purpose structure
     *
     * @return a single structure containing all tasks in the correct order, which contains sequencing of certain tasks. (i.e. 1-2, 2-3 and 1-3 turns into 1-2-3)
     */
    public static ScheduleStructure generalizeStructure(List<ScheduleStructure> structures)
    {
        ScheduleStructure baseStructure = structures.getFirst();
        Map<Machine, List<Task>> generalizedTaskOrder = new HashMap<>();

        for (Machine machine : baseStructure.getMachines())
        {
            List<Task> baseTasks = baseStructure.getTaskOrder(machine).stream().filter(task -> !task.isOptional() && task.getExcludeTasks().isEmpty()).toList(); //just mandatory task list

            Map<Integer, Map<Task, Set<Task>>> orderRelations = new HashMap<>(); //task order dependencies
            Map<Integer, Set<Task>> allOptionalTasks = new HashMap<>();

            for (ScheduleStructure structure : structures)
            {
                List<Task> tasks = structure.getMachines().stream()
                        .filter(structureMachine -> structureMachine.getName().equals(machine.getName()))
                        .findFirst()
                        .map(structure::getTaskOrder)
                        .orElse(List.of());

                int mandatoryIndex = -1; //position counter
                List<Task> currentOptionalBlock = new ArrayList<>();

                for (Task task : tasks)
                {
                    if (!task.isOptional() && task.getExcludeTasks().isEmpty()) // Mandatory
                    {
                        if (!currentOptionalBlock.isEmpty() && mandatoryIndex >= 0)
                        {
                            orderRelations.computeIfAbsent(mandatoryIndex, map -> new HashMap<>());
                            allOptionalTasks.computeIfAbsent(mandatoryIndex, name -> new HashSet<>());
                            allOptionalTasks.get(mandatoryIndex).addAll(currentOptionalBlock);

                            //build relation dependency between tasks into pairs in form of (A -> B)
                            for (int i = 0; i < currentOptionalBlock.size(); i++)
                            {
                                for (int j = i + 1; j < currentOptionalBlock.size(); j++)
                                {
                                    Task Task1 = currentOptionalBlock.get(i);
                                    Task Task2 = currentOptionalBlock.get(j);

                                    orderRelations.get(mandatoryIndex).computeIfAbsent(Task1, task2 -> new HashSet<>()).add(Task2);
                                }
                            }
                            currentOptionalBlock.clear();
                        }
                        mandatoryIndex++;
                    }
                    else
                    {
                        currentOptionalBlock.add(task);
                    }
                }

                if (!currentOptionalBlock.isEmpty() && mandatoryIndex >= 0) //if block exists from last task from loop
                {
                    orderRelations.computeIfAbsent(mandatoryIndex, map -> new HashMap<>());
                    allOptionalTasks.computeIfAbsent(mandatoryIndex, name -> new HashSet<>());
                    allOptionalTasks.get(mandatoryIndex).addAll(currentOptionalBlock);

                    //build relation dependency between tasks into pairs in form of (A -> B)
                    for (int i = 0; i < currentOptionalBlock.size(); i++)
                    {
                        for (int j = i + 1; j < currentOptionalBlock.size(); j++)
                        {
                            Task Task1 = currentOptionalBlock.get(i);
                            Task Task2 = currentOptionalBlock.get(j);

                            orderRelations.get(mandatoryIndex).computeIfAbsent(Task1, task2 -> new HashSet<>()).add(Task2);
                        }
                    }
                    currentOptionalBlock.clear();
                }
            }

            //Generalizing the task order
            List<Task> resultTasks = new ArrayList<>();

            for (int i = 0; i < baseTasks.size(); i++)
            {
                resultTasks.add(baseTasks.get(i));

                if (allOptionalTasks.containsKey(i))
                {
                    Set<Task> nodes = allOptionalTasks.get(i);
                    Map<Task, Set<Task>> edges = orderRelations.getOrDefault(i, new HashMap<>());

                    // Topological Sort
                    Map<Task, Integer> inDegree = new HashMap<>();

                    for (Task task : nodes)
                    {
                        inDegree.put(task, 0);
                    }

                    for (Set<Task> targets : edges.values())
                    {
                        for (Task target : targets)
                        {
                            inDegree.put(target, inDegree.getOrDefault(target, 0) + 1);
                        }
                    }

                    Queue<Task> queue = new LinkedList<>();

                    for (Map.Entry<Task, Integer> entry : inDegree.entrySet())
                    {
                        if (entry.getValue() == 0)
                        {
                            queue.add(entry.getKey());
                        }
                    }

                    Set<String> alreadyInserted = resultTasks.stream().map(Task::getName).collect(Collectors.toSet());

                    while (!queue.isEmpty())
                    {
                        Task currentTask = queue.poll();
                        if(!alreadyInserted.contains(currentTask.getName()))
                        {
                            resultTasks.add(currentTask);
                            alreadyInserted.add(currentTask.getName());
                        }

                        for (Task neighbor : edges.getOrDefault(currentTask, Set.of()))
                        {
                            inDegree.put(neighbor, inDegree.get(neighbor) - 1);

                            if (inDegree.get(neighbor) == 0)
                            {
                                queue.add(neighbor);
                            }
                        }
                    }
                }
            }
            generalizedTaskOrder.put(machine, resultTasks);
        }
        return new ScheduleStructure(generalizedTaskOrder);
    }


    /**
     * Generates a textual diagram of the structure of a given schedule.
     *
     * @return a printable string describing the structure.
     */
    @Override
    public String toString() {
        StringBuilder output = new StringBuilder();

        output.append("--------------------------------------").append(System.lineSeparator());
        for (Machine machine : this.getMachines()) {
            output.append(machine.getName()).append(": ");

            List<Task> tasks = this.structure.get(machine);
            for (int i = 0; i < tasks.size(); i++) {
                output.append(tasks.get(i).getName());
                if (i < tasks.size() - 1) {
                    output.append(" -> ");
                }
            }
            output.append(System.lineSeparator());
        }
        output.append("--------------------------------------").append(System.lineSeparator());
        return output.toString();
    }
}
